---
- name: (browser) google chrome add key
  apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present
  become: yes

- name: (browser) google chrome add repository
  apt_repository:
    repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    state: present
    update_cache: yes
  become: yes

- name: (browser) install browser
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - midori
    - chromium
    - chromium-l10n
    - firefox-esr
    - google-chrome-stable
  become: yes
