---
- name: (fish) add dependencies
  apt:
    name: python-apt
    state: present
    update_cache: yes

- name: (fish) add key
  apt_key:
    url: "http://download.opensuse.org/repositories/shells:fish:release:2/Debian_{{ ansible_distribution_major_version }}.0/Release.key"
    state: present

- name: (fish) add repository
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_{{ ansible_distribution_major_version }}.0/ /"
    filename: "fish"
    state: present
    update_cache: yes

- name: (fish) install fish
  apt:
    name: fish
    state: present