---
- name: (sshd) banner
  template:
    src: sshd_banner.j2
    dest: /etc/ssh/sshd_banner
    force: yes
  become: yes

- name: (sshd) configure sshd
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    force: yes
  become: yes

- name: (sshd) restart
  service:
    name: sshd
    enabled: true
    state: started
  when: ansible_virtualization_type != 'docker'
  become: yes